import type { Editor } from '@tiptap/core';
import type { Transaction } from '@tiptap/pm/state';

const COMPOSITION_SETTLE_RETRY_MS = 20;
const MAX_COMPOSITION_SETTLE_RETRIES = 4;
const COMPOSITION_SETTLE_QUIET_MS = 24;
const COMPOSITION_SETTLE_MAX_MS = 240;

export interface ControlledCompositionRange {
  from: number;
  to: number;
}

export interface ControlledCompositionSnapshot {
  id: number;
  range: ControlledCompositionRange | null;
  text: string | null;
}

type CompositionSettledHandler = (
  editor: Editor,
  snapshot: ControlledCompositionSnapshot,
) => void;

function inputTypeOf(event: Event): string {
  const inputType = (event as InputEvent).inputType;
  return typeof inputType === 'string' ? inputType : '';
}

function inputDataOf(event: Event): string | null {
  const data = (event as InputEvent).data;
  return typeof data === 'string' ? data : null;
}

function isCommittedInput(event: Event): boolean {
  return inputTypeOf(event) === 'insertFromComposition';
}

/**
 * Tracks the browser-owned part of a controlled TipTap composition.
 *
 * WebKit can expose the provisional Latin spelling to ProseMirror, dispatch
 * `compositionend`, and only then deliver the committed CJK text. Merely
 * delaying `onChange` leaves both strings in the document. This controller
 * keeps the original composition range mapped through every transaction and
 * gives the owning editor one bounded opportunity to replace that range with
 * the committed text after the browser has finished its DOM flush.
 */
export class ControlledEditorComposition {
  private active = false;
  private committedInputSeen = false;
  private committedText: string | null = null;
  private compositionData: string | null = null;
  private deadline = 0;
  private generation = 0;
  private awaitingCommittedTransaction = false;
  private range: ControlledCompositionRange | null = null;
  private rangeFrozen = false;
  private settling = false;
  private settleAt = 0;
  private settleHandler: CompositionSettledHandler | null = null;
  private settleEditor: Editor | null = null;
  private sessionId = 0;
  private timer: ReturnType<typeof setTimeout> | null = null;

  /** Start tracking the selection that the browser is about to compose over. */
  start(editor?: Editor | null): void {
    // compositionupdate is allowed to call this method as well. Do not reset
    // the range for every update—the first selection is the stable anchor.
    if (this.active) {
      if (!this.range && editor && !editor.isDestroyed) {
        this.range = this.selectionRange(editor);
      }
      return;
    }

    this.generation += 1;
    this.cancelTimer();
    this.active = true;
    this.awaitingCommittedTransaction = false;
    this.committedInputSeen = false;
    this.committedText = null;
    this.compositionData = null;
    this.deadline = 0;
    this.range =
      editor && !editor.isDestroyed ? this.selectionRange(editor) : null;
    this.rangeFrozen = false;
    this.settling = false;
    this.settleAt = 0;
    this.settleEditor = null;
    this.settleHandler = null;
    this.sessionId += 1;
  }

  /**
   * Keep the composition range aligned with ProseMirror's current document.
   * This includes the transaction generated when a browser first exposes the
   * provisional pinyin and the transaction generated by a late committed
   * input event.
   */
  recordTransaction(transaction: Transaction): void {
    if (
      (!this.active && !this.settling) ||
      !this.range ||
      this.rangeFrozen ||
      !transaction.docChanged
    ) {
      return;
    }
    const from = transaction.mapping.map(this.range.from, -1);
    const to = transaction.mapping.map(this.range.to, 1);
    this.range = {
      from: Math.min(from, to),
      to: Math.max(from, to),
    };
    if (this.settling && this.awaitingCommittedTransaction) {
      this.awaitingCommittedTransaction = false;
      this.rangeFrozen = true;
    }
  }

  /** Observe beforeinput/input without taking ownership of the browser event. */
  noteInput(event: Event): void {
    const data = inputDataOf(event);
    const committed = isCommittedInput(event);

    if (this.active) {
      // A few WebKit versions send insertFromComposition before
      // compositionend. Record it now, but let end() decide when to settle.
      if (committed && data) {
        this.committedInputSeen = true;
        this.committedText = data;
        // Both beforeinput and input are delivered before ProseMirror's
        // MutationObserver flush. Keep the range mappable until the resulting
        // document transaction arrives; freezing on input would leave a late
        // commit outside the tracked pinyin range ("ni hao你好").
        this.awaitingCommittedTransaction = true;
      }
      return;
    }

    if (!this.settling) return;

    // The synthetic/older WebKit path reports the final value as insertText.
    // Only accept it when it matches compositionend's data; this keeps a fast
    // ordinary keystroke after a composition from being swallowed.
    const matchesCompositionData = Boolean(
      data && this.compositionData && data === this.compositionData,
    );
    if (!committed && !matchesCompositionData) {
      // An ordinary key arrived before a delayed composition commit. Freeze
      // the old composition range so normalization cannot consume that key.
      if (data) {
        this.awaitingCommittedTransaction = false;
        this.rangeFrozen = true;
        this.scheduleQuietSettlement();
      }
      return;
    }
    if (data) this.committedText = data;
    this.committedInputSeen = true;
    // The input event itself is still ahead of ProseMirror's DOM observer.
    // Wait for recordTransaction() to map the range and freeze it.
    this.awaitingCommittedTransaction = true;
    this.scheduleQuietSettlement();
  }

  /**
   * End a composition. The two-argument form is retained for the Markdown and
   * presentation editors; document editing passes compositionend.data as the
   * middle argument so late WebKit input can be distinguished from typing.
   */
  end(
    editor: Editor,
    dataOrHandler: string | null | undefined | CompositionSettledHandler,
    maybeHandler?: CompositionSettledHandler,
  ): void {
    const legacySettlement = typeof dataOrHandler === 'function';
    const data = legacySettlement ? null : dataOrHandler;
    const handler =
      typeof dataOrHandler === 'function' ? dataOrHandler : maybeHandler;
    if (!handler || (!this.active && !this.settling)) return;

    if (typeof data === 'string') {
      this.compositionData = data;
      if (data && !this.committedText) this.committedText = data;
      if (data && this.currentRangeText(editor) === data) {
        this.committedInputSeen = true;
        // The document may already contain the committed text, but WebKit can
        // still deliver a second DOM mutation after compositionend. Keep the
        // range mappable until the quiet settlement so a duplicate append is
        // folded into the same correction instead of surviving beside it.
      }
    }

    const generation = ++this.generation;
    this.cancelTimer();
    this.active = false;
    this.settling = true;
    this.deadline = Date.now() + COMPOSITION_SETTLE_MAX_MS;
    this.settleEditor = editor;
    this.settleHandler = handler;
    this.settleAt = legacySettlement
      ? Date.now()
      : this.committedInputSeen
        ? Date.now() + COMPOSITION_SETTLE_QUIET_MS
        : this.deadline;
    if (legacySettlement) {
      this.deadline =
        Date.now() +
        COMPOSITION_SETTLE_RETRY_MS * MAX_COMPOSITION_SETTLE_RETRIES;
    }
    this.scheduleSettlement(generation);
  }

  isBlocking(editor?: Editor | null): boolean {
    return (
      this.active ||
      this.settling ||
      Boolean(editor && !editor.isDestroyed && editor.view.composing)
    );
  }

  destroy(): void {
    this.generation += 1;
    this.cancelTimer();
    this.active = false;
    this.settling = false;
    this.committedInputSeen = false;
    this.committedText = null;
    this.compositionData = null;
    this.deadline = 0;
    this.range = null;
    this.rangeFrozen = false;
    this.settleAt = 0;
    this.settleEditor = null;
    this.settleHandler = null;
  }

  private selectionRange(editor: Editor): ControlledCompositionRange {
    return {
      from: editor.state.selection.from,
      to: editor.state.selection.to,
    };
  }

  private currentRangeText(editor: Editor): string | null {
    if (!this.range || editor.isDestroyed) return null;
    const maximum = editor.state.doc.content.size;
    if (
      this.range.from < 0 ||
      this.range.to < this.range.from ||
      this.range.to > maximum
    ) {
      return null;
    }
    return editor.state.doc.textBetween(
      this.range.from,
      this.range.to,
      '\n',
      '\n',
    );
  }

  private snapshot(editor: Editor): ControlledCompositionSnapshot {
    const maximum = editor.state.doc.content.size;
    const from = this.range
      ? Math.max(0, Math.min(maximum, this.range.from))
      : null;
    const to = this.range
      ? Math.max(0, Math.min(maximum, this.range.to))
      : null;
    return {
      id: this.sessionId,
      range:
        from === null || to === null
          ? null
          : { from: Math.min(from, to), to: Math.max(from, to) },
      text: this.committedText,
    };
  }

  private scheduleQuietSettlement(): void {
    if (!this.settling) return;
    this.settleAt = Math.min(
      this.deadline,
      Date.now() + COMPOSITION_SETTLE_QUIET_MS,
    );
    this.scheduleSettlement(this.generation);
  }

  private scheduleSettlement(expectedGeneration: number): void {
    this.cancelTimer();
    const wait = Math.max(0, this.settleAt - Date.now());
    this.timer = setTimeout(() => {
      this.timer = null;
      if (expectedGeneration !== this.generation || !this.settling) return;
      const editor = this.settleEditor;
      const handler = this.settleHandler;
      if (!editor || !handler || editor.isDestroyed) {
        this.clearSettlement();
        return;
      }
      if (editor.view.composing) {
        if (Date.now() < this.deadline) {
          this.settleAt = Math.min(
            this.deadline,
            Date.now() + COMPOSITION_SETTLE_RETRY_MS,
          );
          this.scheduleSettlement(expectedGeneration);
        } else {
          this.clearSettlement();
        }
        return;
      }
      if (Date.now() < this.settleAt) {
        this.scheduleSettlement(expectedGeneration);
        return;
      }

      // Keep settling=true while the owner normalizes the document. Its
      // synchronous onUpdate callback must still be suppressed for that
      // corrective transaction.
      const snapshot = this.snapshot(editor);
      try {
        handler(editor, snapshot);
      } finally {
        this.clearSettlement();
      }
    }, wait);
  }

  private clearSettlement(): void {
    this.active = false;
    this.awaitingCommittedTransaction = false;
    this.settling = false;
    this.committedInputSeen = false;
    this.committedText = null;
    this.compositionData = null;
    this.deadline = 0;
    this.range = null;
    this.rangeFrozen = false;
    this.settleAt = 0;
    this.settleEditor = null;
    this.settleHandler = null;
  }

  private cancelTimer(): void {
    if (this.timer === null) return;
    clearTimeout(this.timer);
    this.timer = null;
  }
}
