import type { ChapterKind, HomeLanguage } from './HomeEditorContent';

/**
 * Static captures generated by the Office visual regression suite.
 *
 * Keeping the asset map in one place prevents the product home and the
 * chapter gallery from drifting apart. These are captures of the mounted
 * editors, not hand-drawn marketing mockups.
 */
export const editorScreenshotFiles: Record<ChapterKind, string> = {
  document: 'document.png',
  markdown: 'markdown.png',
  spreadsheet: 'spreadsheet.png',
  presentation: 'presentation.png',
  pdf: 'pdf.png',
};

export const editorScreenshotLabels: Record<
  HomeLanguage,
  Record<ChapterKind, string>
> = {
  zh: {
    document: '文档编辑器',
    markdown: 'Markdown 编辑器',
    spreadsheet: '表格编辑器',
    presentation: '演示文稿编辑器',
    pdf: 'PDF 查看器',
  },
  en: {
    document: 'Document editor',
    markdown: 'Markdown editor',
    spreadsheet: 'Spreadsheet editor',
    presentation: 'Presentation editor',
    pdf: 'PDF viewer',
  },
};
