export const WORK_SLIDE_ANIMATION_LIMIT = 256;
export const WORK_SLIDE_ANIMATION_MIN_DURATION_MS = 100;
export const WORK_SLIDE_ANIMATION_MAX_DURATION_MS = 60_000;
export const WORK_SLIDE_ANIMATION_MAX_DELAY_MS = 60_000;
